services:
  mysql:
    image: mysql:8.4
    container_name: mysql-nlw
    environment:
    - MYSQL_ROOT_PASSWORD=user
    - MYSQL_DATABASE=desbraveapi
    - MYSQL_USER=desbrave
    - MYSQL_PASSWORD=user
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - nlw-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s

  app:
    depends_on:
    - mysql
    build: .
    container_name: api_desbrave
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/desbraveapi
      - SPRING_DATASOURCE_USERNAME=desbrave
      - SPRING_DATASOURCE_PASSWORD=user
    ports:
      - "8081:8080"
    networks:
      - nlw-network

networks:
  nlw-network:
    driver: bridge

volumes:
  mysql_data:
