version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-nlw
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: desbraveapi
      MYSQL_USER: desbrave
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nlw-network

volumes:
  mysql_data:
    driver: local

networks:
  nlw-network:
    driver: bridge